apiVersion: v1
kind: Service
metadata:
  name: prakash-headless-service
spec:
  selector:
    app: prakash-runit
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
#      targetPort: 9092