apiVersion: v1
kind: Service
metadata:
  name: prakash-external-runit-service
spec:
  selector:
    app: prakash-runit
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
#      targetPort: 9092